process_noise: [0.001, 0.0, 0.0, 0.0,
                0.0, 0.001, 0.0, 0.0, 
                0.0, 0.0, 0.1, 0.0,
                0.0, 0.0, 0.0, 0.1]

initial_state_covariance: [0.01, 0.0, 0.0, 0.0,
                           0.0, 0.01, 0.0, 0.0, 
                           0.0, 0.0, 0.1, 0.0,
                           0.0, 0.0, 0.0, 0.1]

observation_matrix: [1.0, 0.0, 0.0, 0.0,
                     0.0, 1.0, 0.0, 0.0]

alpha: 0.99
